### PR TITLE
Scanner changes and updates

### PR DESCRIPTION
**Pull request by frinzell**

### CODE REVIEW

**Review by npmitche — APPROVED** [review]

**Comment by 0xfede7c8** [comment]
Are these only naming changes right?

**Comment by frinzell** [comment]
Essentially.  Mostly comments, a few routine name changes, and pointer to updated default json.

**Comment by 0xfede7c8** [comment]
Ok, I will run some smoke tests to check that nothing breaks because of missing changes somewhere.

**Comment by 0xfede7c8** [comment]
> Ok, I will run some smoke tests to check that nothing breaks because of missing changes somewhere.

Run a few tests and did not detect anything new.

**Review by mjkyung — APPROVED** [review]

**Pull request merged**
