### PR TITLE
Changes to uefi decompress functions

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
Created hal.uefi_fv to contain uefi_fv functions
Modified Guids to use UUID
function cleanup

Signed-off-by: brentholtsclaw <brent.holtsclaw@intel.com>

### CODE REVIEW

**Comment by BrentHoltsclaw** [comment]
@0xfede7c8 have you had a chance to review

**Comment by 0xfede7c8** [comment]
Sorry, totally missed this. I will do.

**Comment by BrentHoltsclaw** [comment]
This request has been sitting too long.  If there are not any objections will merge into next release.

**Comment by 0xfede7c8** [comment]
I found something. When running

``` bash
 python ./chipsec_main.py --no_driver -n -m tools.uefi.whitelist -a generate,hashes.json,<image>
```

Where <image> being the attached file, I'm getting:

```bash
[x][ =======================================================================
[x][ Module: simple white-list generation/checking for (U)EFI firmware
[x][ =======================================================================
[*] reading firmware from '/home/xfede/Desktop/test_chipsec_brent/$01DF000.FL1'...
[*] generating a list of EFI executables from firmware image...
ERROR: Exception occurred during chipsec.modules.tools.uefi.whitelist.run(): ''module' object has no attribute 'SECTION_NAMES''

[CHIPSEC] ***************************  SUMMARY  ***************************
[CHIPSEC] Time elapsed            0.273
[CHIPSEC] Modules total           1
[CHIPSEC] Modules failed to run   1:
ERROR: chipsec.modules.tools.uefi.whitelist
[CHIPSEC] Modules passed          0:
[CHIPSEC] Modules information     0:
[CHIPSEC] Modules failed          0:
[CHIPSEC] Modules with warnings   0:
[CHIPSEC] Modules not implemented 0:
[CHIPSEC] Modules not applicable  0:
[CHIPSEC] Modules with exceptions 1:
ERROR: chipsec.modules.tools.uefi.whitelist
[CHIPSEC] *****************************************************************
```


[$01DF000.zip](https://github.com/chipsec/chipsec/files/4805667/01DF000.zip)

**Comment by BrentHoltsclaw** [comment]
Good Find.  Updated Whitelist.py to incorporate changes.

**Comment by 0xfede7c8** [comment]
Another one. Same command with the attached image.

```bash
ERROR: Exception occurred during chipsec.modules.tools.uefi.whitelist.run(): 'unpack requires a string argument of length 4'
```

[IM144_0183_B00.zip](https://github.com/chipsec/chipsec/files/4806451/IM144_0183_B00.zip)

**Comment by 0xfede7c8** [comment]
I didn't find any more problems. Do we want to fix these warnings?

**Pull request merged**
