### PR TITLE
Remove duplicate definitions from processor cfg

### PR DESCRIPTION
**Pull request by tweksteen**
These fields are now defined in the associated PCH configuration.

### CODE REVIEW

**Comment by tweksteen** [comment]
No worries, that sounds good. I wonder if we should have a more obvious warning if the PCH is not recognised? (to make sure these get reported and not become the source of other issues).

**Comment by ErikBjorge** [comment]
It looks like we are missing some of the mobile chipset information and removing these entries would cause a problem.  Let me work on getting them submitted and then we can merge this change.

**Comment by BrentHoltsclaw** [comment]
@ErikBjorge what's the status of this PR?

**Comment by BrentHoltsclaw** [comment]
@ErikBjorge if conflicts are resolved can this be merged?

**Comment by npmitche** [comment]
Closing as it's a stale PR and we are in the process of redefining how chipsec configurations are defined. If needed, please re-open from tip of default branch.

**Pull request closed without merging**
