### PR TITLE
extend chipsec_main search to both py and pyc

### PR DESCRIPTION
**Pull request by tallu**

### CODE REVIEW

**Review by Sae86 — APPROVED** [review]

**Review by BrentHoltsclaw — APPROVED** [review]

**Comment by npmitche** [comment]
@tallu if you want to open a new PR around this that fixes the issue mentioned in #1357, please do!

**Comment by tallu** [comment]
@npmitche How can I regenerate the ERROR described here https://github.com/chipsec/chipsec/pull/1357
    On Friday, January 28, 2022, 08:50:40 PM GMT+2, Nathaniel Mitchell ***@***.***> wrote:  
 
 


@tallu if you want to open a new PR around this that fixes the issue mentioned in #1357, please do!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by npmitche** [comment]
Hi @tallu, simply running chipsec_main.py twice, the first time builds the extra .pyc files, then on the subsequent runs it sees them and errors out.
[pycprlog.txt](https://github.com/chipsec/chipsec/files/7975010/pycprlog.txt)

**Comment by tallu** [comment]
Hi 
What does it mean to strip out pyc files?How do you do that?
Deleting __pycache__ folders is a workaround for this problem.I've added the following lines at the begining of chipsec_main.py and it does the trick...
import pathlibimport shutil[shutil.rmtree(p) for p in pathlib.Path('.').rglob('__pycache__')]
Regards,Tal
    On Tuesday, February 1, 2022, 02:13:24 AM GMT+2, Nathaniel Mitchell ***@***.***> wrote:  
 
 


Hi @tallu, simply running chipsec_main.py twice, the first time builds the extra .pyc files, then on the subsequent runs it sees them and errors out.
pycprlog.txt

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by npmitche** [comment]
Hi @tallu 
Sorry for the lack of response. What is your use case for wanting to include .pyc files? Are you moving .pyc files that were cached on a different system without moving the source (.py)? I'm not sure if that's a viable way to run python code. 

If you simply want python to use the cached bytecodes (.pyc) instead of using the source (.py), this is done automatically when .pyc files are present and this patch is not needed.

**Pull request merged**
