### PR TITLE
Clean up HALs and Helpers

### PR DESCRIPTION
**Pull request by npmitche**
Relies on #1802

### CODE REVIEW

**Review by BrentHoltsclaw — COMMENTED** [review]
are changes needed to linuxnative?

**Comment by npmitche** [comment]
> are changes needed to linuxnative?

It went in clean I think. If there's something that I missed, please let me know.

**Comment by BrentHoltsclaw** [comment]
> > are changes needed to linuxnative?
> 
> It went in clean I think. If there's something that I missed, please let me know.

Looks like it is still using a high and low physical address

https://github.com/npmitche/chipsec/blob/npmitche/cleanhalsandhelpers/chipsec/helper/linuxnative/linuxnativehelper.py#L290
https://github.com/npmitche/chipsec/blob/npmitche/cleanhalsandhelpers/chipsec/helper/linuxnative/linuxnativehelper.py#L297

**Comment by npmitche** [comment]
Fixed a bug I introduced and fixed linux native helper. Thanks!

**Review by dscott90 — APPROVED** [review]

**Review by Sae86 — APPROVED** [review]

**Pull request merged**
