### PR TITLE
Fixup spi_uefi File/Section parsing

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
#776 
Signed-off-by: BrentHoltsclaw <brent.holtsclaw@intel.com>

### CODE REVIEW

**Comment by BrentHoltsclaw** [comment]
@johnloucaides can you help validate the pull request?

**Comment by 0xfede7c8** [comment]
I will test with a bunch of images from different vendors and report back.

I will also propose the creation of a test suite for the UEFI parser, where we can store different images and the expected results. This way we can test changes faster in the future. I will create an issue for this and implement it if the schedule helps.

**Comment by BrentHoltsclaw** [comment]
@0xfede7c8 any concern with this Pull Request?

**Comment by 0xfede7c8** [comment]
I have performed the manual test and didn't find anything bad. In fact I saw some extraction improvements for some images (more executables found). And I feel a small speed improvement, also.

**Comment by 0xfede7c8** [comment]
I have found this one: 
https://github.com/chipsec/chipsec/issues/792

I don't know if this pull request is intended to fix this issue but this bug seems to be present on both current master as well as this branch.

**Pull request merged**
