### PR TITLE
Fix for 'unexport of the kallsyms_lookup_name function' in kernels from 5.7.0 on

### PR DESCRIPTION
**Pull request by PaintedBlck**
Hi,

in follow up of topic _**Blackarch - DKMS make error #953**_, please find the patch I have written.

I have tried to be as less intrusive as possible. The functional logic of the program has not been changed. The only file that is patched is drivers/linux/chipsec_km.c

The patch is _**tested on Blackarch 5.7.7-arch1-1**_

_**!!! P L E A S E   T E S T   T H I S   P A T C H  !!!  on other Linux OS'es**_

Kind regards,
PaintedBlck

### CODE REVIEW

**Comment by iherna2** [comment]
@PaintedBlck I tried this patch on a system I have running 5.7.0 and it fails to load the module. 

I added a couple of extra printk statements and the symbol that is failing to resolve is phys_mem_access_prot, register_kprobe returns error -22 (-EINVAL i believe).

I am guessing there is some config difference between the kernel you run and mine. Can you share your .config?

Do you have any other ideas to try?

**Comment by PaintedBlck** [comment]
_**In reply of your question**_

I have put the kernel build `.config` in the github repo [PaintedBlck/chipsec-kernel_5_7_7-config](https://github.com/PaintedBlck/chipsec-kernel_5_7_7-config)

I have also joined the result of a `dkms status` to show that the fixed chipsec module, loads at startup of the kernel.

To make a final test easy, I have changed the /usr/src/chipsec-964.af7fa73/chipsec_km.c with my patched chipsec_km.c (which makes that version numbers of the module, etc. are not changed).

_**Possible problem**_

Would it be possible that the problem with the `kallsyms_lookup_name` is only present at version 5.7.7 and not at previous versions? Now, I'm interfering in all builds from version 5.7.0 on with three `#if` clauses. If so, my patch has to be adapted in the sence:

Replace all `#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,7,0)`
with `#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,7,7)`

**Comment by iherna2** [comment]
@PaintedBlck, I've installed 5.7.8 and the module still fails loading. I need to look closely at the kernel config file you posted to find out what option(s) might be causing the symbols to not resolve.

**Comment by PaintedBlck** [comment]
@iherna2 I have, unfortunately, encountered the same installation problem on the kernel 5.7.8

I will close this pull request and look further for a solution.

**Pull request closed without merging**
