### PR TITLE
Fix decompress pfs and readability

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
Signed-off-by: BrentHoltsclaw <brent.holtsclaw@intel.com>

### CODE REVIEW

**Comment by 0xfede7c8** [comment]
I'm still getting differences between parsing UEFI files with python3 and python2.

Check attached file:

`python ./chipsec_main.py -n -m tools.uefi.whitelist -a generate,hashes.json,6AC10`
`python3 ./chipsec_main.py -n -m tools.uefi.whitelist -a generate,hashes.json,6AC10`

[6AC10.zip](https://github.com/chipsec/chipsec/files/4148183/6AC10.zip)

**Comment by BrentHoltsclaw** [comment]
It looks like the difference in hash is due to the calculation using  bytes (python3) and string (python2).

**Comment by 0xfede7c8** [comment]
A few questions:

> It looks like the difference in hash is due to the calculation using bytes (python3) and string (python2).

You mean that this patch should fix the problem? 

Is the idea to support two languages in the same codebase? It feels a bit weird to me. At least have two different branches seems a good idea.

**Comment by BrentHoltsclaw** [comment]
This patch does not fix the issue.  Python 2 and 3 were taking different decompression paths because python3 did not understand pfs.  This patch is to fix that piece.

**Comment by BrentHoltsclaw** [comment]
The plan is to drop support for Python 2 after June 2020 until then we need to maintain 2/3 compatibility

**Comment by 0xfede7c8** [comment]
Is this going to be merged? I understood that this patch shouldn't fix the python2 python3 issues so I don't see any other problems.

**Pull request merged**
