### PR TITLE
Fix issue #479

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
Added error handling for when EFI_SECTION_GUID_DEFINED is not large enough to contain dataoffset and attributes

### CODE REVIEW

**Comment by 0xfede7c8** [comment]
What happens with the section's data when this happens? Is the data retrievable or valid?

**Comment by BrentHoltsclaw** [comment]
The error was occurring because the section image is not large enough to extract the guid information, DataOffset, and attributes.  The section data is essentially non-existent.  I put in a warning for the logger to report the inconsistency as something is not correct.  sec.DataOffset is only used if the sec.Guid matches one of the compression guids.  I created a fake guid of 0000-00-00-0000 to ensure that no errors are created and decompression will continue.

**Comment by 0xfede7c8** [comment]
Thanks for the clarification! Another one: Then, that fake guid and broken section will show up somewhere? In the json or lst files maybe?

**Comment by BrentHoltsclaw** [comment]
It will show up at the top of the .lst file as

> WARNING: EFI Section seems to be malformed

**Pull request merged**
