### PR TITLE
Add ability to only display result deltas from previous test run.

### PR DESCRIPTION
**Pull request by ErikBjorge**
This allow the user to check for changes in test results or over time.
This can include the additon or removal of test as well as changes in
test results.

Signed-off-by: Erik Bjorge <erik.c.bjorge@intel.com>

### CODE REVIEW

**Comment by tweksteen** [comment]
How does this work if I just want to compare two JSON results without re-running the test suite? I would also suggest extracting the comparison code and store it in a separate file/method within chipsec/.

**Comment by ErikBjorge** [comment]
Thanks for the feedback @tweksteen. I will split the code out into its own module.  Would using chipsec_util be fine for just checking two JSON log files?

**Comment by ismaws** [comment]
How about presenting/exporting results in XML format?

**Comment by ErikBjorge** [comment]
I can look at adding XML output support as well.  I do not want to deal with using XML as an input format for log file deltas.

**Comment by tweksteen** [comment]
Yep, that sounds good to me. Thanks for implementing this!

**Pull request merged**
