### PR TITLE
Introduce a new module to check for the presence and configuration of the WSMT table.

### PR DESCRIPTION
**Pull request by assafcarlsbad**
The Windows SMM Security Mitigation Table (WSMT) is an ACPI table defined by Microsoft that allows system firmware to confirm to the operating system that certain security best practices have been implemented in System Management Mode (SMM) software.

This PR introduces a new module to check for the presence and configuration of this table. Along the way, it also fixes some bugs related to the retrieval and parsing of other ACPI tables.

### CODE REVIEW

**Comment by assafcarlsbad** [comment]
Works fine on my machine:
```
C:\Users\carlsbad\Code\chipsec [wsmt_module +113 ~1 -0 !]> python .\chipsec_main.py --no_driver -m common.wsmt
################################################################
##                                                            ##
##  CHIPSEC: Platform Hardware Security Assessment Framework  ##
##                                                            ##
################################################################
[CHIPSEC] Version 1.6.2
[CHIPSEC] Arguments: --no_driver -m common.wsmt

[CHIPSEC] API mode: using OS native API (not using CHIPSEC kernel module)
ERROR: chipsec kernel driver is not loaded (in native API mode?)
ERROR: chipsec kernel driver is not loaded (in native API mode?)
[!]       Unknown Platform: VID = 0xFFFF, DID = 0xFFFF, RID = 0xFF; Using Default.
[!]       Unknown PCH: VID = 0xFFFF, DID = 0xFFFF, RID = 0xFF; Using Default.
[!]            Results from this system may be incorrect.
[CHIPSEC] OS      : Windows 10 10.0.19041 AMD64
[CHIPSEC] Python  : 3.9.1 (64-bit)
[CHIPSEC] Helper  : Win32Helper (None)
[CHIPSEC] Platform: UnknownPlatform
[CHIPSEC]      VID: FFFF
[CHIPSEC]      DID: FFFF
[CHIPSEC]      RID: FF
[CHIPSEC] PCH     : Default PCH
[CHIPSEC]      VID: FFFF
[CHIPSEC]      DID: FFFF
[CHIPSEC]      RID: FF

[+] loaded chipsec.modules.common.wsmt
[*] running loaded modules ..

[*] running module: chipsec.modules.common.wsmt
[x][ =======================================================================
[x][ Module: WSMT Configuration
[x][ =======================================================================
------------------------------------------------------------------
Windows SMM Mitigations Table (WSMT) Contents
------------------------------------------------------------------
FIXED_COMM_BUFFERS                  : True
COMM_BUFFER_NESTED_PTR_PROTECTION   : True
SYSTEM_RESOURCE_PROTECTION          : True

[+] PASSED: WSMT table is present and reports all supported mitigations

[CHIPSEC] ***************************  SUMMARY  ***************************
[CHIPSEC] Time elapsed            0.000
[CHIPSEC] Modules total           1
[CHIPSEC] Modules failed to run   0:
[CHIPSEC] Modules passed          1:
[+] PASSED: chipsec.modules.common.wsmt
[CHIPSEC] Modules information     0:
[CHIPSEC] Modules failed          0:
[CHIPSEC] Modules with warnings   0:
[CHIPSEC] Modules not implemented 0:
[CHIPSEC] Modules not applicable  0:
[CHIPSEC] *****************************************************************
```

What OS are you running CHIPSEC on?

**Comment by assafcarlsbad** [comment]
@npmitche Can you please run the same command with debug flags for extra verbosity? (`-v`, `--hal`, etc).

**Comment by npmitche** [comment]
> @npmitche Can you please run the same command with debug flags for extra verbosity? (`-v`, `--hal`, etc).

```
[*] running module: chipsec.modules.common.wsmt
[+] imported: chipsec.modules.common.wsmt
[*] Module path: .\chipsec\modules\common\wsmt.py
[x][ =======================================================================
[x][ Module: WSMT Configuration
[x][ =======================================================================
[acpi] trying to enumerate ACPI tables from physical memory...
[acpi] searching RSDP in EBDA..
[mem] 0x000000000000040E
[mem] 0x00000000000E0000
[acpi] searching RSDP pointers in EFI Configuration Table..
[cpu0] RDMSR( 0xfe ): EAX = 0x00005D0A, EDX = 0x00000000
[*] MTRRCAP = 0x00005D0A << MTRR Capabilities MSR (MSR 0xFE)
    [00] VCNT             = A << Variable Range Registers Count 
    [08] Fixed_Range_MTRR = 1 << Fixed range MTRRs Supported 
    [10] WC               = 1 << WC Supported 
    [11] SMRR             = 1 << SMRR Supported 
    [12] PRMRR            = 1 << PRMRR Supported 
[cpu0] RDMSR( 0x1f2 ): EAX = 0x4A000006, EDX = 0x00000000
[cpu0] RDMSR( 0x1f3 ): EAX = 0xFF000C00, EDX = 0x00000000
[uefi] searching memory for EFI table with signature 'IBI SYST' ..
[uefi] reading 0x0000000049F00000..
[mem] 0x0000000049F00000
...
[uefi] found signature 'IBI SYST' at 0x0000000040E3A018..
[uefi] found EFI table at 0x0000000040E3A018 with signature 'IBI SYST'..
49 42 49 20 53 59 53 54 46 00 02 00 78 00 00 00 | IBI SYSTF   x   
99 CB D1 31 00 00 00 00 18 CF FA 54 04 F8 FF FF |    1       T    
13 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 |                 
00 00 00 00 00 00 00 00 98 EB 12 55 04 F8 FF FF |            U    
00 00 00 00 00 00 00 00 0E 00 00 00 00 00 00 00 |                 
98 EC 12 55 04 F8 FF FF                         |    U    
[uefi] EFI System Table:
Header:
  Signature     : IBI SYST
  Revision      : 2.70
  HeaderSize    : 0x00000078
  CRC32         : 0x31D1CB99
  Reserved      : 0x00000000
EFI System Table:
  FirmwareVendor      : 0xFFFFF80454FACF18
  FirmwareRevision    : 0x0000000000050013
  ConsoleInHandle     : 0x0000000000000000
  ConIn               : 0x0000000000000000
  ConsoleOutHandle    : 0x0000000000000000
  ConOut              : 0x0000000000000000
  StandardErrorHandle : 0x0000000000000000
  StdErr              : 0x0000000000000000
  RuntimeServices     : 0xFFFFF8045512EB98
  BootServices        : 0x0000000000000000
  NumberOfTableEntries: 0x000000000000000E
  ConfigurationTable  : 0xFFFFF8045512EC98
[uefi] UEFI appears to be in Runtime mode
[mem] VA (0xFFFFF8045512EC98) -> PA (0x0000000040E3AC98)
[uefi] EFI Configuration Table (14 entries): VA = 0xFFFFF8045512EC98, PA = 0x0000000040E3AC98
[mem] 0x0000000040E3AC98
[-] Traceback (most recent call last):
  File "chipsec_main.py", line 159, in run_module
    result = modx.run( module_argv )
  File ".\chipsec\module.py", line 87, in run
    result = self.mod_obj.run(module_argv)
  File ".\chipsec\modules\common\wsmt.py", line 72, in run
    self.res = self.check_wsmt()
  File ".\chipsec\modules\common\wsmt.py", line 47, in check_wsmt
    acpi = ACPI(self.cs)
  File ".\chipsec\hal\acpi.py", line 241, in __init__
    self.get_ACPI_table_list()
  File ".\chipsec\hal\acpi.py", line 396, in get_ACPI_table_list
    (is_xsdt, sdt_pa, sdt, sdt_header) = self.get_SDT()
  File ".\chipsec\hal\acpi.py", line 361, in get_SDT
    (rsdp_pa, rsdp) = self.find_RSDP()
  File ".\chipsec\hal\acpi.py", line 346, in find_RSDP
    rsdp, rsdp_pa = self._find_RSDP_in_EFI_config_table()
  File ".\chipsec\hal\acpi.py", line 297, in _find_RSDP_in_EFI_config_table
    (isFound, ect_pa, ect, ect_buf) = self.uefi.find_EFI_Configuration_Table()
  File ".\chipsec\hal\uefi.py", line 607, in find_EFI_Configuration_Table
    ect.VendorTables[ vt.VendorGuid() ] = vt.VendorTable
  File ".\chipsec\hal\uefi_common.py", line 971, in VendorGuid
    return EFI_GUID_STR(self.VendorGuid)
  File ".\chipsec\hal\uefi_common.py", line 203, in EFI_GUID_STR
    guid_str = UUID(bytes_le=guid)
  File "C:\Python\Python38\lib\uuid.py", line 174, in __init__
    if len(bytes_le) != 16:
TypeError: object of type 'method' has no len()
ERROR: Exception occurred during chipsec.modules.common.wsmt.run(): 'object of type 'method' has no len()'
[-] Traceback (most recent call last):
  File "chipsec_main.py", line 278, in run_loaded_modules
    result = self.run_module( modx, modx_argv )
  File "chipsec_main.py", line 165, in run_module
    raise msg
  File "chipsec_main.py", line 159, in run_module
    result = modx.run( module_argv )
  File ".\chipsec\module.py", line 87, in run
    result = self.mod_obj.run(module_argv)
  File ".\chipsec\modules\common\wsmt.py", line 72, in run
    self.res = self.check_wsmt()
  File ".\chipsec\modules\common\wsmt.py", line 47, in check_wsmt
    acpi = ACPI(self.cs)
  File ".\chipsec\hal\acpi.py", line 241, in __init__
    self.get_ACPI_table_list()
  File ".\chipsec\hal\acpi.py", line 396, in get_ACPI_table_list
    (is_xsdt, sdt_pa, sdt, sdt_header) = self.get_SDT()
  File ".\chipsec\hal\acpi.py", line 361, in get_SDT
    (rsdp_pa, rsdp) = self.find_RSDP()
  File ".\chipsec\hal\acpi.py", line 346, in find_RSDP
    rsdp, rsdp_pa = self._find_RSDP_in_EFI_config_table()
  File ".\chipsec\hal\acpi.py", line 297, in _find_RSDP_in_EFI_config_table
    (isFound, ect_pa, ect, ect_buf) = self.uefi.find_EFI_Configuration_Table()
  File ".\chipsec\hal\uefi.py", line 607, in find_EFI_Configuration_Table
    ect.VendorTables[ vt.VendorGuid() ] = vt.VendorTable
  File ".\chipsec\hal\uefi_common.py", line 971, in VendorGuid
    return EFI_GUID_STR(self.VendorGuid)
  File ".\chipsec\hal\uefi_common.py", line 203, in EFI_GUID_STR
    guid_str = UUID(bytes_le=guid)
  File "C:\Python\Python38\lib\uuid.py", line 174, in __init__
    if len(bytes_le) != 16:
TypeError: object of type 'method' has no len()
```

It looks like it's only showing up in Windows.

**Comment by assafcarlsbad** [comment]
The bug was caused because `VendorGuid` was used both as method name as well as a name for a `namedtuple` member, so I don't think it's related to any of the new code introduced by this PR.

```
class EFI_VENDOR_TABLE( namedtuple('EFI_VENDOR_TABLE', 'VendorGuid VendorTable') ):
    __slots__ = ()
    def VendorGuid(self):
        return EFI_GUID_STR(self.VendorGuid)
```

I fixed it by simply referring to it using an index rather than a name:
```
class EFI_VENDOR_TABLE( namedtuple('EFI_VENDOR_TABLE', 'VendorGuid VendorTable') ):
    __slots__ = ()
    def VendorGuid(self):
        return EFI_GUID_STR(self[0])
```

@npmitche Can you please verify these finding and the bugfix?

**Comment by npmitche** [comment]
That looks like it works, but it's not very readable. Could you change it to:
```python
class EFI_VENDOR_TABLE( namedtuple('EFI_VENDOR_TABLE', 'RawVendorGuid VendorTable') ):
    __slots__ = ()
    def VendorGuid(self):
        return EFI_GUID_STR(self.RawVendorGuid)
```
 Looks like we haven't been using the ACPI class, so this bug has gone undetected for a while.  Thanks for debugging it!

**Comment by assafcarlsbad** [comment]
Done.

**Review by npmitche — APPROVED** [review]

**Review by BrentHoltsclaw — APPROVED** [review]

**Review by Sae86 — APPROVED** [review]

**Pull request merged**
