### PR TITLE
Fix memory allocation bug in smm_ptr

### PR DESCRIPTION
**Pull request by npmitche**
Signed-off-by: Nathaniel Mitchell <nathaniel.p.mitchell@intel.com>

### CODE REVIEW

**Review by dscott90 — APPROVED** [review]

**Review by Sae86 — APPROVED** [review]

**Comment by minipli-oss** [comment]
I think the limitation to allocate memory with a physical address below 4GB was intentional. Why do you remove that limitation, i.e. what's the bug?

**Comment by npmitche** [comment]
Yeah, I think you might be right. I'm still investigating.  This is why it has not been merged in yet. 🤔

**Comment by minipli-oss** [comment]
And what's the bug? Can you point me to an issue or provide some logs?

I fixed allocation errors for smm_ptr in PR #1389 specifically. Maybe I broke something else with these fixes?

**Comment by npmitche** [comment]
Closing due to wrong implementation of fix.

**Comment by minipli-oss** [comment]
Well, my fix made sure we're actually using the correct physical address while the old code was silently truncating the allocated address to 32 bit. The the old code, while "working", is doing the wrong thing -- passing a bogus address to the SMI handler.

Can you provide more verbose logs?

**Comment by npmitche** [comment]
Yeah, you're right. In the "working" dmesg I see this:
```
[  549.384400] auto freeing allocated memory (va = 000000004e05855c, pa = 0x10df89000)
[  549.384402] auto freeing allocated memory (va = 00000000b9095912, pa = 0x10df8b800)
[  657.131309] Chipsec module loaded 
[  657.131313] ** This module exposes hardware & memory access, **
[  657.131313] ** which can effect the secure operation of      **
[  657.131314] ** production systems!! Use for research only!   **
[  657.709046] [chipsec] WARNING: allocated memory (0x10472e000) is not below max_pa (0xffffffff) (ignoring)
[  657.709108] [chipsec] WARNING: allocated memory (0x10472f800) is not below max_pa (0xffffffff) (ignoring)
[  657.711767] [chipsec] > IOCTL_SWSMI
[  657.714356] [chipsec] > IOCTL_SWSMI
```

**Comment by npmitche** [comment]
If I comment out:
```python
if (max_pa > 16 * 1024 * 1024)
			va = kmalloc(NumberOfBytes, GFP_KERNEL | GFP_DMA32);
```
It looks like it works. When I looking at the kmalloc api, I don't see a GFP_DMA32 flag definition, just the GFP_DMA one. 
https://www.kernel.org/doc/htmldocs/kernel-api/API-kmalloc.html

**Comment by minipli-oss** [comment]
Can you provide the log of the non-working version, please?

GFP_DMA32 is supposed to return an address below 4GB while GFP_DMA will allocate from the legacy DMA area below 16MB. However, the latter might be occupied by the kernel itself, so the driver tries to use GFP_DMA32 first. But without logs, hard to tell what happens on your system.

**Comment by npmitche** [comment]
[errorlog1.txt](https://github.com/chipsec/chipsec/files/9201225/errorlog1.txt)

**Pull request closed without merging**
