### PR TITLE
Changes logger functions based on #1361

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
Depends on #1361 

- Convert logging to use log_hal, log_verbose, log_debug when applicable.
- Convert uses of logger.warn into logger.log_warning
- Convert uses of logger.error into logger.log_error
- Remove use of logger _check functions

### CODE REVIEW

**Comment by frinzell** [comment]
Just the APIs right now. Plus this will be in smaller doses.

**Comment by ErikBjorge** [comment]
What patch size would you find more acceptable for this type of cleanup?  I'm sure these could be submitted over time with 10 or so files per PR.

**Comment by BrentHoltsclaw** [comment]
Is this an acceptable size or do I need to break up the 3 commits into separate PRs?

**Comment by frinzell** [comment]
Let's pick up during our next sync.

**Pull request closed without merging**
