### PR TITLE
Intel DAL helper

### PR DESCRIPTION
**Pull request by frinzell**

### CODE REVIEW

**Comment by rhapsodyjay** [comment]
Seems i can't import chipsec_util and chipsec_man in DAL console.




2018-07-26 2:27 GMT+08:00 BrentHoltsclaw <notifications@github.com>:

**Comment by frinzell** [comment]
Hi,

Thank you for contacting us.  Can you elaborate on the error message or behavior you are seeing?

The chipsec-manual.pdf has some installation steps that might be helpful.

Thanks,

Aaron

**Comment by rhapsodyjay** [comment]
Yes, I installed chipset follow the PDF and it can run. Then I merged the
dal helper change. Then I installed Intel system debugger but I can't start
up dal Pythonconsole.cmd successfully. It says can't find the module
'utils'(I didn't capture the screen shot of this). Then I start up
cscripts, it can run . Then I import chipsec_util, it fails as the
screenshot .

Aaron Frinzell <notifications@github.com> 於 2018年7月27日 週五 下午11:06 寫道：

**Comment by rhapsodyjay** [comment]
Typo, I installed chipsec .

Jay Chang <rhapsodyjay99@gmail.com> 於 2018年7月28日 週六 上午12:03 寫道：

**Comment by frinzell** [comment]
Try using the Windows pywin32 installer.

**Comment by frinzell** [comment]
I saw the 'utils' issue when using the ‘pip install pypiwin32' install.  Using pywin32 Windows Extensions from [here](http://sourceforge.net/projects/pywin32/) should work.

**Comment by rhapsodyjay** [comment]
i installed pywin32-223.win-amd64-py2.7, still see this:



2018-07-28 4:23 GMT-07:00 Igor Skochinsky <notifications@github.com>:

**Comment by frinzell** [comment]
Contact me at chipsec@intel.com for debugging this.

**Comment by ErikBjorge** [comment]
What is the current status on the issues reported above @frinzell?  Just want to see if the issues have been resolved and it can be merged?

**Comment by frinzell** [comment]
Issue resolved and not related to this PR.  There was a DAL/pip dependency break when updating the python environment via one particular method of update.  It's captured as a troubleshooting step for the wiki.
Can be merged.

**Pull request merged**
