### PR TITLE
Fix decompression bug

### PR DESCRIPTION
**Pull request by PerezFederico**
Fix a decompression issue causing crashes and probably a security vulnerability.
It is a fix also for something I did wrong in another commit that was merged.

### CODE REVIEW

**Comment by PerezFederico** [comment]
I also fixed Issue #310 that was added by myself. Sorry.

**Comment by BrentHoltsclaw** [comment]
Line 781 should handle this case (where compression size is larger than the input buffer), however it does not account for the fact that compsize +8 could overflow and cause fillbuf to read outside of the input like you are seeing.

**Comment by PerezFederico** [comment]
Let me see if I understand.
You mean this?

       if (SrcSize < CompSize + 8) {
         return EFI_INVALID_PARAMETER;
         }

To this?

       if (SrcSize <= CompSize + 8) {
         return EFI_INVALID_PARAMETER;
         }

**Comment by BrentHoltsclaw** [comment]
I am proposing adding a check for compsize + 8 to ensure it did not overflow (i.e. 0xFFFFFFF9 +8).  Something like this:
```
if (SrcSize < CompSize + 8 || (CompSize + 8) < 8 ) {
     return EFI_INVALID_PARAMETER;
     }
```

**Comment by PerezFederico** [comment]
I understood now. Done. Good catch.

**Comment by ErikBjorge** [comment]
So for some reason it seems that VERSION was included on the branch and when merged it lost our development tag.  This is not a big deal but could have been worse if it happened with some other code changes.  In the future it might be better to rebase the branch before merging.  I tend to use the rebase and merge option to detect this type of conflict.  Rebase and merge also forces a linear history.

No worries, I have submitted a new pull request to fix this very minor issue.

**Pull request merged**
