### PR TITLE
Add ability to parse non-UEFI section data

### PR DESCRIPTION
**Pull request by BrentHoltsclaw**
Attempt to address #1790.  Add ability to parse for modules when a large section of unidentified data is found.

### CODE REVIEW

**Comment by BrentHoltsclaw** [comment]
@npmitche is there a need to enable/disable this code?

**Review by dscott90 — APPROVED** [review]

**Comment by npmitche** [comment]
> @npmitche is there a need to enable/disable this code?

I don't really see a reason to be able to enable/disable it. Do you see a reason?

**Comment by BrentHoltsclaw** [comment]
@platomav  @npmitche 
Ran a comparison of this PR (with #1890), chipsec_current (with #1890) and uefi extract.  The results can be interpreted as follows:
line 1 - contains the two programs being compared and the binary
line2 - contains a list any unique files based upon GUID within the first program listed and the second program listed.
in the example below there were no unique files found by either program.
```
UEFIExtract CHIPSEC tgl73.bin :
{'uniqueGUIDS1': [], 'uniqueGUIDS2': []}
```
In the next example, CHIPSEC found a file that UEFIExtract did not
```
UEFIExtract CHIPSEC HP-EliteBook-1040g7-i7-10610U-mmio.bin :
{'uniqueGUIDS1': [], 'uniqueGUIDS2': ['4E655FBD-4919-04E9-1967-4FB92018EB03']}
```
[decompress_compare.log](https://github.com/chipsec/chipsec/files/11987007/decompress_compare.log)

Based upon the results, the new code does not seem to miss any results that the current version of chipsec finds.

**Comment by platomav** [comment]
@BrentHoltsclaw 

Very nice roundup! I've been wanting to do something similar (i.e. UEFIExtract vs Chipsec) for some time now but on a much-much larger data set, which will allow both tools to improve from each other's coverage/detections.

Regarding UEFIExtract, I'm fairly certain that you run it on Windows using an older commit/version because the many missing detections seem to be related to:

https://github.com/LongSoft/UEFITool/issues/363

That issue affected Windows because of the MAX_PATH limitation, but it has been addressed since June 20th by using UNC paths in those cases. For example, if you re-run the tests with the latest commit (as of now, https://github.com/LongSoft/UEFITool/commit/a5675bda90145715ddda9169ae644a053f7ec93f), you should not see missing GUIDs at "6d271ea0a7c4b0846404790fd9a7791bb3781be2_R101acer.Cap" sample.

Another possible indicator of using an older UEFIExtract version is the fact that I'm able to find the (seemingly missing) GUID "166C533A-8F1E-4D34-A60E-0F68D8D61308" when checking manually the "Lenovo-0AHJ000.FL2" sample image:

Screenshot 2023-07-09 143820

I also see cases in which UEFIExtract detected GUIDs that Chipsec + PR missed:

- HP-SpectreX360-i7-8565U-mmio.bin
- Supermicro-X11ssm-mmio.bin
    - A0327FE0-1FDA-4E5B-905D-B510C45A61D0
- 2f23b45580eacbade578a3c5568dd9e2bec260fb_SHW4.Cap
   - 48B92674-F889-22A8-7E0A-7D0DD1940040

Another (important) sample which I think should be kept/tested is the one with the "hidden" LenovoComputraceLoader binaries within an NVRAM-like area: "233baa0298ff7e9d46479868bbeb45948cbf649f_BIOS.cap". For this case, Chipsec + PR should be able to detect the 5 Computrace binaries (based on our discussion at https://github.com/chipsec/chipsec/issues/1790#issuecomment-1553325595). UEFIExtract will not detect these Computrace binaries yet because https://github.com/LongSoft/UEFITool/issues/366 fix is pending. But at least for Chipsec, it would be good to check that sample from now on and verify that those 5 uncharted binaries do get detected.

Last but not least, the last section of the log file (Chipsec vs Chipsec + PR) shows that there are no regressions compared to the old Chipsec release, based on this small sample set of course, which is good.

Now, regarding this PR, our last discussion was centered around these observations/goals:

https://github.com/chipsec/chipsec/issues/1790#issuecomment-1561855323

So, do you think that the current code covers all cases of "uncharted" volume/section/file within unexpected areas (e.g. Non-UEFI, RAW, Padding, NVRAM)?

In order to accomplish that, is it needed to scan will all 3 functions in "unexpected" areas?

Will there be a problem with "duplicate" GUID/binary detections because Chipsec will scan with more than one possible function for volumes/sections/files, or will these be automatically merged without a problem (crash, overwritten results which are different etc)? I'm asking just in case, because I'm not familiar with how Chipsec handles the multiple results internally.

**Review by npmitche — APPROVED** [review]

**Comment by npmitche** [comment]
Hi @BrentHoltsclaw, what is the status on this PR?

**Comment by BrentHoltsclaw** [comment]
> Hi @BrentHoltsclaw, what is the status on this PR?

Would like verification that it does not break functionality.  It is working from my point of view.  @platomav and @npmitche can you please validate this is the case?

**Comment by platomav** [comment]
@npmitche @BrentHoltsclaw 

The current blocker for testing this is https://github.com/chipsec/chipsec/issues/1888, as explained last month at https://github.com/chipsec/chipsec/issues/1790#issuecomment-1644499721

**Comment by platomav** [comment]
In case it got missed, I performed a check for the efficacy of this PR and found an issue, compared to before:

- https://github.com/chipsec/chipsec/issues/1790#issuecomment-1702763645

**Review by Sae86 — APPROVED** [review]

**Review by npmitche — APPROVED** [review]

**Pull request merged**
